set background=dark

set nocompatible
let mapleader = "\<Space>"
nmap <Leader>rxm :ExtractMethod<Enter>

"==============================================="
call plug#begin('~/.vim/plugged')
set nocompatible
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'rafi/awesome-vim-colorschemes'
"//TODO: C/C++ and tabulations and other"
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'flazz/vim-colorschemes'
Plug 'kien/ctrlp.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-fugitive'
" Commenting
Plug 'tomtom/tlib_vim'
Plug 'ryanoasis/vim-devicons'
Plug 'tomtom/tcomment_vim'
" Auto-close brackets
Plug 'jiangmiao/auto-pairs' 
call plug#end()

"~/AppData/Local/nvim/plugged

filetype plugin on
filetype indent on

syntax enable




"======== Main shit ============="

"colorscheme archery
colorscheme nord
syntax on
set hlsearch
set incsearch
let mapleader = ","
let g:mapleader = ","
set lines=999 columns=110
let g:enable_bold_font = 1 
set history=700
set wildmenu
set tabstop=4
set title
set number
set cursorline
set noswapfile
set nobackup
set nowb
set t_Co=256
set softtabstop=0 noexpandtab
set shiftwidth=4
set noerrorbells
set vb t_vb=
set guioptions=
set showtabline=0
set noswapfile
set wildmenu
set encoding=utf-8
set keymap=russian-jcukenmac
set iminsert=0
set imsearch=0
set backspace=indent,eol,start
set fileencoding=utf-8
set termencoding=utf-8
"auto close br"

"========= GVIM FONT ==========================="
set guifont=Source\ Code\ Pro\ for\ Powerline:h11:cANSI
"=============== C/C++ =============="
set omnifunc=ccomplete#Complete

"================= NERDTree ===================="
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
let NERDTreeQuitOnOpen = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

"=============== AIR-LINE SHIT ================="
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'
let g:airline_solarized_bg='base16'
let g:airline_powerline_fonts = 1
let g:Powerline_symbols='unicode'
let g:airline#extensions#xkblayout#enabled = 0

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = ' '
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''

